#!/bin/sh

set -e

if [ ! -f /etc/lsb_release ] && [ ! -f /etc/debian_version ]
then
    echo "Script is meant to install packages on Debian/Ubuntu based distributions"
    echo "Pleas install dependencies manually on other distributions"
    exit 1
fi

apt-get update
apt-get -y install build-essential build-essential gcc-mingw-w64 g++-mingw-w64 texinfo flex bison libmpfr-dev libgmp-dev libmpc-dev zip